// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfMEUJi89Sa5VqUd3A_ywCGEVpvcBJvHY',
    appId: '1:847788316106:web:00ed3a0d7e8328f1b96b33',
    messagingSenderId: '847788316106',
    projectId: 'datingapp-61962',
    authDomain: 'datingapp-61962.firebaseapp.com',
    storageBucket: 'datingapp-61962.firebasestorage.app',
    measurementId: 'G-LQ99KBTJ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1r-7_bndkJnkkOvaACzIkYP1AEgRfo-s',
    appId: '1:847788316106:android:73e8869b22fe06e1b96b33',
    messagingSenderId: '847788316106',
    projectId: 'datingapp-61962',
    storageBucket: 'datingapp-61962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzhyD7XuH6GNJpTJ-at0sz7oprK2uVMAQ',
    appId: '1:847788316106:ios:247e3443e49501c9b96b33',
    messagingSenderId: '847788316106',
    projectId: 'datingapp-61962',
    storageBucket: 'datingapp-61962.firebasestorage.app',
    iosBundleId: 'com.reversematch.reverse-match',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhyD7XuH6GNJpTJ-at0sz7oprK2uVMAQ',
    appId: '1:847788316106:ios:247e3443e49501c9b96b33',
    messagingSenderId: '847788316106',
    projectId: 'datingapp-61962',
    storageBucket: 'datingapp-61962.firebasestorage.app',
    iosBundleId: 'com.reversematch.reverse-match',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfMEUJi89Sa5VqUd3A_ywCGEVpvcBJvHY',
    appId: '1:847788316106:web:730e78207c0b17edb96b33',
    messagingSenderId: '847788316106',
    projectId: 'datingapp-61962',
    authDomain: 'datingapp-61962.firebaseapp.com',
    storageBucket: 'datingapp-61962.firebasestorage.app',
    measurementId: 'G-6R13GVKF25',
  );
}
